---
title: "First Knit"
author: "Emma DeAscentis"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "8/22/24"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  I attended Quartz Hill Highschool and was apart of the graduating class of 2021.I was always an English kind of student, but was one to struggle in both subjects however english is much easier for me. Nonetheless, history was always the class I scored the best. 

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  I have internet connection but no personal computer, my skills are about a four out of ten, sadly. 
  
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  Nothing!I am Emma and please call me that! Thank you for asking though!
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  I want to help someone in this world th way others have helped me, whether I pursue that dream through psychology or business I plan on making that difference. I would like to be a therapist who specializes in sexual trauma and PTSD EMDR therapy. On the business side Id love to open a thrift store with a tailor in store. 
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
   I wish i have been to foriegn countries! Someday australia and europe,  maybe japan
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  I need to pass this class for my future, but for myself the most. Maintaining my goals is all I hold close to my heart. 
   
 






  




